export const queryKeys = {
  homeSummary: () => ["home-summary"] as const,
  adminOrders: (queryString = "") => ["admin-orders", queryString] as const,
  adminUsers: (queryString: string) => ["admin-users", queryString] as const,
  categories: () => ["categories"] as const,
  customerOrders: (queryString = "") => ["customer-orders", queryString] as const,
  meals: (queryString: string) => ["meals", queryString] as const,
  meal: (id: string) => ["meal", id] as const,
  mealReviews: (mealId: string) => ["meal-reviews", mealId] as const,
  myProviderProfile: () => ["my-provider-profile"] as const,
  myUserProfile: () => ["my-user-profile"] as const,
  myAddresses: () => ["my-addresses"] as const,
  order: (id: string) => ["order", id] as const,
  providerMeals: (providerId: string) => ["provider-meals", providerId] as const,
  providerOrders: (queryString = "") => ["provider-orders", queryString] as const,
  providerAnalytics: (days: number) => ["provider-analytics", days] as const,
  providers: (queryString: string) => ["providers", queryString] as const,
  provider: (id: string) => ["provider", id] as const,
  adminCoupons: (queryString = "") => ["admin-coupons", queryString] as const,
  adminAnalytics: (days: number) => ["admin-analytics", days] as const,
  mealFavorites: (queryString: string) => ["meal-favorites", queryString] as const,
  providerFavorites: (queryString: string) => ["provider-favorites", queryString] as const,
  mealFavoriteState: (mealId: string) => ["meal-favorite-state", mealId] as const,
  providerFavoriteState: (providerId: string) => ["provider-favorite-state", providerId] as const,
} as const;
